In [1]:
import numpy as np
import pandas as pd

ca_meta = pd.read_csv('../ca/ca_meta.csv')
gba_meta = ca_meta[ca_meta.District == 4]
gba_meta = gba_meta.reset_index()
gba_meta = gba_meta.drop(columns=['index'])
gba_meta.to_csv('gba_meta.csv', index=False)
print(gba_meta[gba_meta.duplicated(subset=['Lat', 'Lng'])])
gba_meta

Empty DataFrame
Columns: [ID, Lat, Lng, District, County, Fwy, Lanes, Type, Direction, ID2]
Index: []

,ID,Lat,Lng,District,County,Fwy,Lanes,Type,Direction,ID2
0,404356,38.015867,-122.182664,4,Contra Costa,SR4-E,2,Mainline,E,480
1,402518,38.015347,-122.179054,4,Contra Costa,SR4-E,2,Mainline,E,481
2,402516,38.006871,-122.166606,4,Contra Costa,SR4-E,2,Mainline,E,482
3,402214,38.001498,-122.150137,4,Contra Costa,SR4-E,2,Mainline,E,483
4,402212,37.995777,-122.144977,4,Contra Costa,SR4-E,2,Mainline,E,484
...,...,...,...,...,...,...,...,...,...,...
2347,401273,37.803541,-122.279977,4,Alameda,I980-W,3,Mainline,W,2827
2348,401137,37.806967,-122.278034,4,Alameda,I980-W,3,Mainline,W,2828
2349,401610,37.810554,-122.275579,4,Alameda,I980-W,4,Mainline,W,2829
2350,401416,37.814242,-122.271837,4,Alameda,I980-W,5,Mainline,W,2830
2351,401911,37.818437,-122.270170,4,Alameda,I980-W,3,Mainline,W,2831

In [2]:
gba_meta_id2 = gba_meta.ID2.values.tolist()
print(len(gba_meta_id2))

ca_rn_adj = np.load('../ca/ca_rn_adj.npy')
print(ca_rn_adj.shape)

gba_rn_adj = ca_rn_adj[gba_meta_id2]
gba_rn_adj = gba_rn_adj[:,gba_meta_id2]
print(gba_rn_adj.shape)

np.save('gba_rn_adj.npy', gba_rn_adj)

2352
(8600, 8600)
(2352, 2352)

In [3]:
year = '2019'  # please specify the year, our experiments use 2019

gba_meta.ID = gba_meta.ID.astype(str)
gba_meta_id = gba_meta.ID.values.tolist()

ca_his = pd.read_hdf('../ca/ca_his_' + year +'.h5')
gba_his = ca_his[gba_meta_id]
gba_his

,404356,402518,402516,402214,402212,402210,402835,414294,414295,402513,...,401144,401615,401413,401896,400642,401273,401137,401610,401416,401911
Time,,,,,,,,,,,,,,,,,,,,,
2019-01-01 00:00:00,32.0,52.0,41.0,41.0,41.0,41.0,9.0,16.0,26.0,63.0,...,23.0,1.0,115.0,33.0,27.0,78.0,175.0,35.0,75.0,29.0
2019-01-01 00:15:00,36.0,66.0,35.0,35.0,35.0,35.0,18.0,26.0,38.0,76.0,...,53.0,90.0,189.0,72.0,31.0,100.0,197.0,76.0,111.0,56.0
2019-01-01 00:30:00,42.0,80.0,28.0,28.0,28.0,28.0,40.0,54.0,62.0,90.0,...,69.0,110.0,199.0,78.0,80.0,113.0,198.0,95.0,137.0,68.0
2019-01-01 00:45:00,38.0,77.0,24.0,24.0,24.0,24.0,37.0,51.0,65.0,93.0,...,78.0,121.0,215.0,86.0,106.0,117.0,194.0,107.0,141.0,72.0
2019-01-01 01:00:00,39.0,81.0,21.0,21.0,21.0,21.0,37.0,53.0,62.0,91.0,...,69.0,115.0,211.0,91.0,105.0,110.0,209.0,93.0,129.0,69.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-31 22:45:00,86.0,86.0,86.0,86.0,86.0,86.0,86.0,37.0,44.0,86.0,...,67.0,116.0,134.0,81.0,80.0,86.0,154.0,93.0,105.0,62.0
2019-12-31 23:00:00,76.0,76.0,76.0,76.0,76.0,76.0,76.0,27.0,33.0,76.0,...,59.0,101.0,116.0,65.0,70.0,76.0,140.0,77.0,86.0,55.0
2019-12-31 23:15:00,69.0,69.0,69.0,69.0,69.0,69.0,69.0,27.0,38.0,69.0,...,48.0,80.0,97.0,55.0,34.0,69.0,129.0,66.0,78.0,48.0
2019-12-31 23:30:00,61.0,61.0,61.0,61.0,61.0,61.0,61.0,21.0,37.0,61.0,...,49.0,72.0,86.0,52.0,30.0,61.0,114.0,65.0,72.0,49.0
2019-12-31 23:45:00,53.0,53.0,53.0,53.0,53.0,53.0,53.0,25.0,30.0,53.0,...,43.0,66.0,79.0,53.0,22.0,53.0,117.0,52.0,60.0,42.0

In [4]:
gba_his.to_hdf('gba_his_' + year + '.h5', key='t', mode='w')
gba_his.shape

(35040, 2352)

In [5]:
# code for checking adj stat
gba_rn_adj = np.load('gba_rn_adj.npy')
node_num = gba_rn_adj.shape[0]

print(gba_rn_adj[0,0])
gba_rn_adj[np.arange(node_num), np.arange(node_num)] = 0
print(gba_rn_adj[0,0])

print('edge number', np.count_nonzero(gba_rn_adj))
print('node degree', np.mean(np.count_nonzero(gba_rn_adj, axis=-1)))
print('sparsity', np.count_nonzero(gba_rn_adj) / (node_num**2) * 100)

1.0
0.0
edge number 61246
node degree 26.03996598639456
sparsity 1.1071414109861633